defaults:
  rng_seed: 0xa1221f97
  learning_rate: 1e-5
  gradient_checkpointing: false
  gradient_accumulation_steps: 32
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1e-12
  weight_decay: 0.00
  warmup_steps: 600
  eval_steps: 200
  save_strategy: epoch
  max_length: 512
  val_max_length:
  num_train_epochs: 3
  logging_steps: 10
  max_grad_norm: 2.0
  save_total_limit: 4
  dtype: bf16
  eval_accumulation_steps:
  freeze_layer:
  datasets:
    - webgpt
    - squad_v2
    - adversarial_qa
    - trivia_qa_nocontext
    - xsum
    - cnn_dailymail
    - multi_news
    - scitldr
    - soda:
        input_max_length: 1024
    - joke
    - gsm8k
    - dive_mt
    - wmt2019_zh-en
    - wmt2019_ru-en
    - wmt2019_de-en
    - ted_trans_nl-en
    - ted_trans_de-ja
    - wmt2019_de-en
    - samsum
    - soda_dialogue
  # instructional_datasets:
  #  - humaneval_mbpp_codegen_qa
  #  - humaneval_mbpp_testgen_qa
  #  - grade_school_math_instructions
  #  - recipes
  #  - ubuntu_dialogue_qa
  #  - cmu_wiki_qa
  #  - youtube_subs_howto100M
  #  - iapp_wiki_qa_squad
  #  - zhihu-kol
  datasets_extra: [] # For config options to add additional datasets, since yaml doesn't let us extend arrays
  cache_dir: .cache
  loss_fn: CrossEntropyLoss
  eval_size:
  log_dir: "base"
  quantization: false
  seq2seqmodel: false
  poly_eps: 1.0
  fuse_gelu: true
  log_wandb: true
  samples_mixing: false # uses collator that mixes samples in the batch to create a single sample with possible multiple tasks within
  verbose: false
  output_dir: saved_model
  use_custom_sampler: false
  random_offset_probability: 0.8 # probability for random message offsets
  label_masking: true
  residual_dropout: 0.0
  use_flash_attention: false
  sort_by_length: false
  use_system_prefix: true
  system_prefix:
    "You are StableChat, a large language model trained by StabilityAI. This is a chat between a curious user and you (artificial intelligence assistant). The assistant gives helpful, detailed, and polite answers to the user's questions. "
  use_system_tag: false
  system_property_dropout: 0.5
  system_add_length: false
  per_digit_tokens: false
  is_reward_model: false
  residual_dropout_lima: false
  deepspeed_config: configs/zero_config.json
  peft_model: false
  peft_type: "lora"

use_system_tag:
  use_system_tag: True
  system_property_dropout: 0.5
  system_add_length: True

webgpt_dataset_only:
  datasets:
    - webgpt

per_digit_tokens:
  per_digit_tokens: true

math:
  datasets_extra: # Will get merged with datasets
    - minimath

pretrain:
  num_train_epochs: 1
  weight_decay: 0.0
  use_custom_sampler: true
  sort_by_length: false
  datasets:
    - alpaca_gpt4:
        val_split: 0.025
        max_val_set: 250
    - vicuna:
        val_split: 0.025
        max_val_set: 250
    - gpteacher_roleplay:
        val_split: 0.05
    - red_pajama:
        fraction: 0.25
        max_val_set: 1000
    - wizardlm_70k:
        val_split: 0.05
        max_val_set: 500
    - joke:
        val_split: 0.05
    - poem_instructions:
        val_split: 0.025
    - oa_stackexchange:
        val_split: 0.05
        fraction: 0.1
        max_val_set: 1000
    - tell_a_joke:
        val_split: 0.05
        max_val_set: 250
    - webgpt:
        val_split: 0.05
        max_val_set: 250
    - gpt4all:
        val_split: 0.01
        max_val_set: 1000
    - code_alpaca:
        val_split: 0.05
        max_val_set: 250
    - oig_file:
        source_url: https://huggingface.co/datasets/laion/OIG/resolve/main/unified_chip2.jsonl
        max_count: 10000
        min_length: 250
        val_split: 0.05
        max_val_set: 250
    - minimath:
        val_split: 0.05
    - humaneval_mbpp_codegen_qa:
        val_split: 0.05
    - humaneval_mbpp_testgen_qa:
        val_split: 0.05
    - grade_school_math_instructions:
        val_split: 0.05
    - recipes:
        val_split: 0.05
    - cmu_wiki_qa:
        val_split: 0.05
    - oa_wiki_qa_bart_10000row:
        val_split: 0.05
        max_val_set: 250
    - prosocial_dialogue:
        fraction: 0.1
        max_val_set: 250
    - explain_prosocial:
        fraction: 0.075
        max_val_set: 250
    - soda:
        fraction: 0.25
        max_val_set: 1000
    - oa_leet10k:
        val_split: 0.05
        max_val_set: 250
    - dolly15k:
        val_split: 0.05
        max_val_set: 300

oasst_only:
  save_strategy: epoch
  datasets:
    - oasst_export:
        lang: "bg,ca,cs,da,de,en,es,fr,hr,hu,it,nl,pl,pt,ro,ru,sl,sr,sv,uk"
        hf_dataset_name: OpenAssistant/oasst1
        #input_file_path: 2023-04-12_oasst_ready.trees.jsonl.gz
        #top_k: 1
        val_split: 0.05
  sort_by_length: false
  use_custom_sampler: false

reference-data:
  datasets:
    - oasst_export:
        lang: "bg,ca,cs,da,de,en,es,fr,hr,hu,it,nl,pl,pt,ro,ru,sl,sr,sv,uk"
        input_file_path: 2023-03-25_oasst_research_ready_synth_labels.jsonl.gz
        val_split: 0.05
    - alpaca
  sort_by_length: false
  use_custom_sampler: false

oasst_export_eu:
  save_strategy: epoch
  datasets:
    - oasst_export:
        lang: "en,es,de,fr"
        hf_dataset_name: OpenAssistant/oasst1
    - gpt4all
    - alpaca
    - code_alpaca
    - oig_file:
        source_url: https://huggingface.co/datasets/laion/OIG/resolve/main/unified_chip2.jsonl
        max_count: 10000
        min_length: 100
        val_split: 0.1
    - oig_file:
        source_url: https://huggingface.co/datasets/laion/OIG/raw/main/unified_grade_school_math_instructions.jsonl
        val_split: 0.1
        min_length: 100
  sort_by_length: false
  use_custom_sampler: false

oasst_export_latin_cyrillic:
  save_strategy: epoch
  datasets:
    - oasst_export:
        lang: "bg,ca,cs,da,de,en,es,fr,hr,hu,it,nl,pl,pt,ro,ru,sl,sr,sv,uk"
        hf_dataset_name: OpenAssistant/oasst1
    - alpaca
    - oig_file:
        source_url: https://huggingface.co/datasets/laion/OIG/resolve/main/unified_chip2.jsonl
        max_count: 10000
        min_length: 1000
        val_split: 0.2
    - oig_file:
        source_url: https://huggingface.co/datasets/laion/OIG/raw/main/unified_grade_school_math_instructions.jsonl
        val_split: 0.1
        min_length: 1000
  sort_by_length: false
  use_custom_sampler: false

oasst-top1:
  save_strategy: steps # epoch seems not to work, gets stuck with DS 0.9.1
  save_steps: 600
  datasets:
    - oasst_export:
        lang: "bg,ca,cs,da,de,en,es,fr,hr,hu,it,nl,pl,pt,ro,ru,sl,sr,sv,uk" # sft-8.0
        input_file_path: 2023-05-06_OASST_labels.jsonl.gz
        val_split: 0.05
        top_k: 1

oasst-mix:
  datasets:
    - oasst_export:
        lang: "en"
        input_file_path: 2023-06-02_oasst_all_labels.jsonl.gz
        top_k: 1
    - vicuna:
        val_split: 0.05
        max_val_set: 800
        fraction: 1.0
    - grade_school_math_instructions:
        val_split: 0.05
        fraction: 0.5
    - code_alpaca:
        val_split: 0.05
        max_val_set: 250
    - oa_leet10k:
        val_split: 0.05
        max_val_set: 250
        fraction: 0.2
    - camel:
        val_split: 0.05
        max_val_set: 250
    - airoboros:
        val_split: 0.05
        max_val_set: 250
    - wizard_evol:
        val_split: 0.05
        max_val_set: 250

wizard-only:
  datasets:
    - wizard_evol:
        val_split: 0.05
        max_val_set: 250


chai:
  datasets:
    - soda:
        input_max_length: 1024
    - chai_edit
    - chai_davinci
    - chai_roleplay
    - chai_instruct
    - chai_gpt


gpt-j-6b:
  dtype: bf16
  log_dir: "gptj-6b"
  learning_rate: 2e-5
  model_name: "PygmalionAI/pygmalion-6b"
  deepspeed_config: configs/zero_config.json
  output_dir: /fsx/home-duyphung/chai/pyg-comp
  weight_decay: 0.0
  max_length: 768
  warmup_steps: 50
  gradient_checkpointing: true
  gradient_accumulation_steps: 2
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 1
  eval_steps: 100000
  num_train_epochs: 3 
  save_total_limit: 3 
  use_flash_attention: false
  residual_dropout: 0.0
